#!/usr/bin/with-contenv sh

# Checks for SSH_USER variable
if [ -z "$SSH_USER" ]; then
  echo >&2 'Please set an SSH_USER variable (ie.: -e SSH_USER=john).'
  exit 1
fi

# Checks for PASSWORD variable
if [ -z "$SSH_PASSWORD" ]; then
  echo >&2 'Please set a SSH_PASSWORD variable (ie.: -e SSH_PASSWORD=superstrongpass).'
  exit 1
fi

echo "Creating user ${SSH_USER}"
adduser -D ${SSH_USER} && echo "${SSH_USER}:${SSH_PASSWORD}" | chpasswd
echo "Fixing permissions for user ${SSH_USER}"
chown -R ${SSH_USER}:${SSH_USER} "/home/dropbear"